# apiVersion specifies which version of the Kubernetes API you're using to
# create this object.
apiVersion: v1

# kind specifies what kind of object you want to create (ResourceQuota).
# A ResourceQuota provides constraints that limit aggregate resource consumption
# per namespace.
kind: ResourceQuota

# metadata helps uniquely identify the object, including a name string.
metadata:
  # name is the unique identifier for this ResourceQuota within its namespace.
  name: cpu-quota

# spec defines the desired state or behavior of the ResourceQuota.
spec:
  # hard is the set of desired hard limits for each named resource. Once a
  # limit is reached, no more resources of that type can be created in the
  # namespace.
  hard:
    # requests.cpu limits the total amount of CPU requests that can be
    # requested by all Pods in the namespace to 2 cores.
    requests.cpu: "2"
    
    # limits.cpu specifies that the maximum sum of CPU limits across all Pods
    # in the namespace cannot exceed 4 cores.
    limits.cpu: "4"
    
    # requests.memory limits the total memory requests across all Pods in the
    # namespace to 512 Mebibytes.
    requests.memory: "512Mi"
    
    # limits.memory specifies that the maximum sum of memory limits across all
    # Pods in the namespace cannot exceed 1 Gibibyte.
    limits.memory: "1Gi"
